# Generated by Django 3.1.6 on 2022-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Param_Societe',
            fields=[
                ('raison_social', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('activite', models.CharField(max_length=5000)),
                ('ice_s', models.CharField(max_length=1000)),
                ('if_s', models.CharField(max_length=1000)),
                ('centre_rc', models.CharField(max_length=1000)),
                ('num_rc', models.CharField(max_length=1000)),
                ('capital', models.CharField(max_length=150)),
                ('Forme_juridique', models.CharField(max_length=1000)),
                ('date_creation', models.CharField(max_length=1000)),
                ('effectif', models.CharField(max_length=1000)),
                ('adresse', models.CharField(max_length=5000)),
                ('Etat', models.CharField(max_length=1000)),
                ('Tel', models.CharField(max_length=1000)),
                ('Fax', models.CharField(max_length=1000)),
                ('site_web', models.CharField(max_length=1000)),
                ('Emails', models.CharField(max_length=3000)),
            ],
        ),
    ]
